external:
  rating-service:
    base-url: http://localhost:8081
    connect-timeout: 500ms
    read-timeout: 500ms

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  bulkhead:
    instances:
      bookRating:
        max-concurrent-calls: 10
        max-wait-duration: 0
  circuitbreaker:
    instances:
      bookRating:
        failure-rate-threshold: 50
        minimum-number-of-calls: 4
        permitted-number-of-calls-in-half-open-state: 2
        register-health-indicator: true
        sliding-window-size: 8
        wait-duration-in-open-state: 10s
  retry:
    instances:
      bookRating:
        max-attempts: 2
        wait-duration: 100ms
        retry-exceptions:
          - org.springframework.web.client.RestClientException
