drop table if exists book_comments;
drop table if exists books;
drop table if exists genres;
drop table if exists authors;
drop table if exists application_users;

create table application_users
(
    id       bigint generated by default as identity,
    username varchar(64)  not null unique,
    password varchar(100) not null,
    role     varchar(32)  not null,
    enabled  boolean      not null,
    primary key (id)
);

create table authors
(
    id        bigint generated by default as identity,
    full_name varchar(255) not null,
    primary key (id)
);

create table genres
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table books
(
    id        bigint generated by default as identity,
    title     varchar(255) not null,
    author_id bigint       not null references authors (id) on delete cascade,
    genre_id  bigint       not null references genres (id) on delete cascade,
    primary key (id)
);

create table book_comments
(
    id      bigint generated by default as identity,
    text    varchar(1024) not null,
    book_id bigint        not null references books (id) on delete cascade,
    primary key (id)
);
